#!/bin/bash

if [ "$1" = "" ]; then
echo "Provide on/off argument, --help for options."
exit 0
fi

SERVER=makhost
SERVERLOM=makhost-sp

TEMP=`getopt -o s:l:u:h --long server:,serverlom:,user:,help -n serverpower -- "$@"`
eval set -- "$TEMP"

while true
do
	case "$1" in
		-s|--server)
			case "$2" in
			"")
				SERVER=makhost
				shift 2
				;; 
			*)
				SERVER=$2
				shift 2
				;;
			esac
			;;
		-l|--serverlom)
			case "$2" in
			*)
				SERVERLOM=$2
				shift 2
				;;
			"")
				SERVERLOM=192.168.7.100
				shift 2
				;;
			esac
			;;
		-u|--user)
			case "$2" in
			"")
				USER=tallian
				shift 2
				;;
			*)
				USER=$2
				shift 2
				;;
			esac
			;;
		-h|--help)
			echo "Utility to configure server power using ipmitool and ssh to issue remote commands, give on or off arguments."
			echo "The following command line switches will override the defaults:"
			echo
			echo "   -s or --server will change the default server name or IP"
			echo
			echo "   -l or --serverlom will change the default lom name or IP"
			echo
			echo "   -u or --user will change the default username"
			echo
			echo "  Script will prompt for password as needed."
			exit 0
			;;
		--) shift ; break ;;
	esac
done

echo $SERVER
echo $USER
echo $SERVERLOM

read -sp 'Remote password: ' PASSWORD
echo "\n"

if [ "$1" = "on" ] ; then
ipmitool -U $USER -P $PASSWORD -H $SERVERLOM power $1
elif [ "$1" = "off" ]; then
echo "Checking to see if $SERVER is up..."
ping -c 1 $SERVER > /dev/null
if [ $? -eq 0 ]
then
echo "Powering off server..."
expect -c "
spawn ssh -t $USER@$SERVER sudo poweroff
expect password: { send $PASSWORD\r }
expect password { send $PASSWORD\r }
sleep 1
exit
"
echo "Server shutting down."
else
echo "$SERVER is not currently up and responsive."
fi
fi
