#!/bin/bash

### Declarations
# Variables
VMHOST=192.168.100.1

# Running as root?
if [ "$(whoami)" != "root" ]
then
echo "Please run this with sudo permissions."
exit 1 
fi

### Get parameters from user
read -p "What is the name of the VM:  " VMNAME
read -p "What is the IP address of the VM:  " IPADDR


### Script for installing VMs after building in KVM
#if [ ! $# == 2 ]
#then
#echo
#echo "Please provide a VM name and IP address.  ie":
#echo "     vminstall <VM Name> <VM IP Address>"
#echo
#echo "This will add the VM to the list of managed VMS on this host."
#echo
#echo
#else
ssh -q $VMHOST "echo $VMNAME >> /virt/vmlist"
echo "$IPADDR $VMNAME" >> /etc/hosts
scp -pr /root/ $IPADDR:/
ssh -q $VMHOST virsh -c qemu:///system shutdown $VMNAME
sleep 60
ssh -q $VMHOST cp /virt/active/$VMNAME.* /virt/backup/
ssh -q $VMHOST virsh -c qemu:///system start $VMNAME
#fi
